config/routes.rb
Rails.application.routes.draw do
  get 'home/contact'

  resources :mots
  get 'home/index'

  root 'home#index'

  get 'mots/nouveau' => 'mots#new'

end

app/models/mot.rb
class Mot < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mots_controller.rb
class MotsController < ApplicationController
  before_action :set_mot, only: [:show, :edit, :update, :destroy]

  # GET /mots
  # GET /mots.json
  def index
    @mots = Mot.all
  end

  # GET /mots/1
  # GET /mots/1.json
  def show
  end

  # GET /mots/new
  def new
    @mot = Mot.new
  end

  # GET /mots/1/edit
  def edit
  end

  # POST /mots
  # POST /mots.json
  def create
    @mot = Mot.new(mot_params)

    respond_to do |format|
      if @mot.save
        format.html { redirect_to @mot, notice: 'Le mot a bien été créé.' }
        format.json { render :show, status: :created, location: @mot }
      else
        format.html { render :new }
        format.json { render json: @mot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mots/1
  # PATCH/PUT /mots/1.json
  def update
    respond_to do |format|
      if @mot.update(mot_params)
        format.html { redirect_to @mot, notice: 'Le mot a bien été modifié.' }
        format.json { render :show, status: :ok, location: @mot }
      else
        format.html { render :edit }
        format.json { render json: @mot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mots/1
  # DELETE /mots/1.json
  def destroy
    @mot.destroy
    respond_to do |format|
      format.html { redirect_to mots_url, notice: 'Le mot a bien été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mot
      @mot = Mot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mot_params
      params.require(:mot).permit(:abreviation, :signification)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mots_helper.rb
module MotsHelper
end

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>APEI</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mots/_form.html.erb
<%= form_for(@mot) do |f| %>
  <% if @mot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mot.errors.count, "error") %> prohibited this mot from being saved:</h2>

      <ul>
      <% @mot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :abreviation %><br>
    <%= f.text_field :abreviation %>
  </div>
  <div class="field">
    <%= f.label :signification %><br>
    <%= f.text_field :signification %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mots/edit.html.erb
<h1>Editer un mot</h1>

<%= render 'form' %>

<%= link_to 'Voir', @mot %> |
<%= link_to 'Retour', mots_path %>

app/views/mots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lexique</h1>

<table>
  <thead>
    <tr>
      <th>Abreviation</th>
      <th>Signification</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mots.each do |mot| %>
      <tr>
        <td><%= mot.abreviation %></td>
        <td><%= mot.signification %></td>
        <td><%= link_to 'Voir', mot %></td>
        <td><%= link_to 'Editer', edit_mot_path(mot) %></td>
        <td><%= link_to 'Supprimer', mot, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer ce mot ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau mot', new_mot_path %>

app/views/mots/new.html.erb
<h1>Nouveau mot</h1>

<%= render 'form' %>

<%= link_to 'Retour', mots_path %>

app/views/mots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Abreviation:</strong>
  <%= @mot.abreviation %>
</p>

<p>
  <strong>Signification:</strong>
  <%= @mot.signification %>
</p>

<%= link_to 'Editer', edit_mot_path(@mot) %> |
<%= link_to 'Retour', mots_path %>